<?php

/**
 * @file
 * Contains perls_default_content.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function perls_default_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the perls_default_content module.
    case 'help.page.perls_default_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PERLS Default Content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function perls_default_content_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  $card_types = ['flash_card', 'tip_card', 'quiz'];
  // Forces card view when directly viewing a node.
  if ($view_mode == 'full' && $entity->getEntityTypeId() == 'node' && in_array($entity->getType(), $card_types)) {
    $view_mode = 'card';
  }
}

/**
 * Implements hook_update_N().
 */
function perls_default_content_update_8002(&$sandbox) {
  $default_content = [
    'block_content' => [
      '36b390b0-d87c-4116-9470-2da4abe526d8',
    ],
  ];
  _perls_default_content_delete_content($default_content);
}

/**
 * Deletes install content.
 *
 * @param array $content
 *   Content keyed by entity-type and UUID.
 */
function _perls_default_content_delete_content(array $content) {
  foreach ($content as $entity_type_id => $items) {
    $storage = \Drupal::entityTypeManager()->getStorage($entity_type_id);
    foreach ($items as $uuid) {
      $entity = $storage->loadByProperties(['uuid' => $uuid]);
      $storage->delete($entity);
    }
  }
}
